### ISSUE TITLE
Issue serving all assets into build

### ISSUE THREAD

**Issue by ScorpIan555** [ScorpIan555/real-estate-app#1]
Comparing my staging URL and the theme's Demo URL, it's obvious what's missing when the html is rendered:  

The hero.img image must be rendered by some Javascript, but I've checked everything side by side and can't see what it is specifically that I'm missing in the Asset build.  Can you see anything that jumps out?

One thing I noticed was a .psd file in the theme's folder, but I don't know how to serve that (it's a photoshop file). 

Theme download page: 
http://pixelhint.com/la-casa-free-real-estate-fully-responsive-html5-css3-home-page-template/

Staging/Prod URL:
http://real-estate-sqfxg7.turbo360-vertex.com/

Demo URL:
http://pixelhint.com/demo/la_casa/

Github Repo:
https://github.com/ScorpIan555/real-estate-app

**Comment by Epichris360** [comment]
Check main.css in line 202. that's where the decleration for the path to the image is found.
